noSegments = 14
    inOutSegmentsIds = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    filename.0 = "stl/Lunge_Cut_ASCII.stl"
    filename.1 = "stl/Verschluss_Oben_ASCII.stl"
    filename.2 = "stl/Verschluss_Unten_ASCII.stl"
    filename.3 = "stl/inlet0_mm.stl"
    filename.4 = "stl/23_mm.stl"
    filename.5 = "stl/24_mm.stl"
    filename.6 = "stl/25_mm.stl"
    filename.7 = "stl/26_mm.stl"
    filename.8 = "stl/27_mm.stl"
    filename.9 = "stl/28_mm.stl"
    filename.10 = "stl/29_mm.stl"
    filename.11 = "stl/30_mm.stl"
    filename.12 = "stl/31_mm.stl"
    filename.13 = "stl/32_mm.stl"

    "body_segments.wall" = 0
    "body_segments.vorne" = 1
    "body_segments.hinten" = 2
    "body_segments.inlet" = 3
    "body_segments.23" = 4
    "body_segments.24" = 5
    "body_segments.25" = 6
    "body_segments.26" = 7
    "body_segments.27" = 8
    "body_segments.28" = 9
    "body_segments.29" = 10
    "body_segments.30" = 11
    "body_segments.31" = 12
    "body_segments.32" = 13

    BC.0 = 2000 
    BC.1 = 2000 
    BC.2 = 2000 
    BC.3 = 1000 #fix volume flow rate with variable RE number at outlet (area of throat at outlet)
    BC.4 = 4000 #SanVanor & Wanzel equation from gas dynamics, with density instead of pressure
    BC.5 = 4000
    BC.6 = 4000
    BC.7 = 4000 
    BC.8 = 4000 
    BC.9 = 4000
    BC.10 = 4000
    BC.11 = 4000
    BC.12 = 4000
    BC.13 = 4000
