        noSolvers                       = 2
        multiSolverGrid                 = true
# -------------- APPLICATION SETTINGS  --------------
        flowSolver                      = false   
        gridGenerator                   = true    
        scratchSize                     = 30.0
        dynamicLoadBalancing            = false
# -------------- APPLICATION ENVIRONMENT  --------------
        outputDir                       = "./out_flow/"       
        geometryInputFileName           = "geometry.toml"
	gridOutputFileName              = "grid.Netcdf"  
        gridInputFileName               = "grid.Netcdf"  
# -------------- SPATIAL DISCRETIZATION --------------
        spaceDimensions                 = 3              
# -------------- GRID AND REFINEMENT PROPERTIES --------------  
        maxNoCells                      = 100000000     #Maximale Zellanzahl
        minLevel                        = 11             #Initielles Verfeinerungslevel
        maxUniformRefinementLevel       = 11            #Maximales Verfeinerungslevel für die Geo.
        maxRfnmntLvl                    = 11            #Maximales Verfeinerungslevel
        maxBoundaryRfnLvl               = 11            #Maximales Verfeinerungslevel des Randes
        reductionFactor                 = 1.724137931        #Zur Vergrößerung der Initialgitters
# -------------- REFINEMENT OF THE NASAL CAVITY --------------
        # Set the special refinement type: 0 deactivated, 1 patch only, 2 boundary only, 3 both.
        localRfnMethod                  = 0                             
        
        localBndRfnMethod               = 2

        localRfnBoundaryIds             = [0,1,2,3,4]
        localRfnLvlDiff                 = [0,0,0,0,0]  
        smoothDistance                  = [15,15,15,25,15] 
        localMinBoundaryThreshold       = 1
        localBndRfnDistance             = [2.0,2.0,2.0,2.0,2.0]  