noSegments = 3
inOutSegmentsIds = [0,1]

filename.0 = "stl/inlet.stl" 
filename.1 = "stl/outlet.stl"
filename.2 = "stl/stenotic_pipe.stl"

"body_segments.inlet1"     = 0
"body_segments.outlet1" = 1
"body_segments.wall1"  = 2

BC.0  = 1000
BC.1  = 4000
BC.2  = 2000