noSolvers = 2 # 3BLOCKS: set to 3
multiSolverGrid = true
# -------------- APPLICATION SETTINGS  --------------

flowSolver            = false
gridGenerator         = true
scratchSize           = 20.0

# -------------- APPLICATION ENVIRONMENT  --------------

outputDir             = "out/"
geometryInputFileName = "geometry.toml"
gridOutputFileName    = "grid.Netcdf"

# -------------- SPATIAL DISCRETIZATION --------------

nDim     = 3

# -------------- GRID AND REFINEMENT PROPERTIES --------------

reductionFactor                 = 1.0
maxNoCells                      = 1000000
partitionCellOffspringThreshold = 5000
minLevel                        = 5
maxUniformRefinementLevel       = 5
maxRfnmntLvl                    = 7
maxBoundaryRfnLvl               = 7


# Set the special refinement type: 0 deactivated, 1 patch only, 2 boundary only, 3 both.
localRfnMethod                  = 3

localBndRfnMethod               = 0        
smoothDistance                  = 2
localMinBoundaryThreshold       = 1
localRfnBoundaryIds             = 2

localRfnLvlMethods              = "B-B"
localRfnLevelProperties         = [-0.005, 0.02, -0.005, 0.005, 0.04, 0.005, 
                                   -0.005, 0.026, -0.005, 0.005, 0.04, 0.005, ]